/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wes_client

// Log - Log and other info
type Log struct {

	// The task or workflow name
	Name string `json:"name,omitempty"`

	// The command line that was executed
	Cmd []string `json:"cmd,omitempty"`

	// When the command started executing, in ISO 8601 format \"%Y-%m-%dT%H:%M:%SZ\"
	StartTime string `json:"start_time,omitempty"`

	// When the command stopped executing (completed, failed, or cancelled), in ISO 8601 format \"%Y-%m-%dT%H:%M:%SZ\"
	EndTime string `json:"end_time,omitempty"`

	// A URL to retrieve standard output logs of the workflow run or task.  This URL may change between status requests, or may not be available until the task or workflow has finished execution.  Should be available using the same credentials used to access the WES endpoint.
	Stdout string `json:"stdout,omitempty"`

	// A URL to retrieve standard error logs of the workflow run or task.  This URL may change between status requests, or may not be available until the task or workflow has finished execution.  Should be available using the same credentials used to access the WES endpoint.
	Stderr string `json:"stderr,omitempty"`

	// Exit code of the program
	ExitCode string `json:"exit_code,omitempty"`
}
