/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wes_client

// ServiceInfo - A message containing useful information about the running service, including supported versions and default settings.
type ServiceInfo struct {

	// A map with keys as the workflow format type name (currently only CWL and WDL are used although a service may support others) and value is a workflow_type_version object which simply contains an array of one or more version strings
	WorkflowTypeVersions map[string]WorkflowTypeVersion `json:"workflow_type_versions,omitempty"`

	// The version(s) of the WES schema supported by this service
	SupportedWesVersions []string `json:"supported_wes_versions,omitempty"`

	// The filesystem protocols supported by this service, currently these may include common protocols using the terms 'http', 'https', 'sftp', 's3', 'gs', 'file', or 'synapse', but others  are possible and the terms beyond these core protocols are currently not fixed.   This section reports those protocols (either common or not) supported by this WES service.
	SupportedFilesystemProtocols []string `json:"supported_filesystem_protocols,omitempty"`

	// The engine(s) used by this WES service, key is engine name (e.g. Cromwell) and value is version
	WorkflowEngineVersions map[string]string `json:"workflow_engine_versions,omitempty"`

	// Each workflow engine can present additional parameters that can be sent to the workflow engine. This message will list the default values, and their types for each workflow engine.
	DefaultWorkflowEngineParameters []DefaultWorkflowEngineParameter `json:"default_workflow_engine_parameters,omitempty"`

	// The system statistics, key is the statistic, value is the count of runs in that state. See the State enum for the possible keys.
	SystemStateCounts map[string]int64 `json:"system_state_counts,omitempty"`

	// A web page URL with human-readable instructions on how to get an authorization token for use with a specific WES endpoint.
	AuthInstructionsUrl string `json:"auth_instructions_url,omitempty"`

	// An email address URL (mailto:) or web page URL with contact information for the operator of a specific WES endpoint.  Users of the endpoint should use this to report problems or security vulnerabilities.
	ContactInfoUrl string `json:"contact_info_url,omitempty"`

	// A key-value map of arbitrary, extended metadata outside the scope of the above but useful to report back
	Tags map[string]string `json:"tags,omitempty"`
}
