/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wes_client

// RunRequest - To execute a workflow, send a run request including all the details needed to begin downloading and executing a given workflow.
type RunRequest struct {

	// REQUIRED The workflow run parameterizations (JSON encoded), including input and output file locations
	WorkflowParams map[string]interface{} `json:"workflow_params,omitempty"`

	// REQUIRED The workflow descriptor type, must be \"CWL\" or \"WDL\" currently (or another alternative supported by this WES instance)
	WorkflowType string `json:"workflow_type,omitempty"`

	// REQUIRED The workflow descriptor type version, must be one supported by this WES instance
	WorkflowTypeVersion string `json:"workflow_type_version,omitempty"`

	// OPTIONAL A key-value map of arbitrary metadata outside the scope of `workflow_params` but useful to track with this run request
	Tags map[string]string `json:"tags,omitempty"`

	// OPTIONAL Additional parameters can be sent to the workflow engine using this field. Default values for these parameters can be obtained using the ServiceInfo endpoint.
	WorkflowEngineParameters map[string]string `json:"workflow_engine_parameters,omitempty"`

	// REQUIRED The workflow CWL or WDL document. When `workflow_attachments` is used to attach files, the `workflow_url` may be a relative path to one of the attachments.
	WorkflowUrl string `json:"workflow_url,omitempty"`
}
