/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wes_client

// RunStatus - Small description of a workflow run, returned by server during listing
type RunStatus struct {
	RunId string `json:"run_id"`

	State State `json:"state,omitempty"`
}
