/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package wes_client

// DefaultWorkflowEngineParameter - A message that allows one to describe default parameters for a workflow engine.
type DefaultWorkflowEngineParameter struct {

	// The name of the parameter
	Name string `json:"name,omitempty"`

	// Describes the type of the parameter, e.g. float.
	Type string `json:"type,omitempty"`

	// The stringified version of the default parameter. e.g. \"2.45\".
	DefaultValue string `json:"default_value,omitempty"`
}
