version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - (cd ~/.goenv; git pull)
      - goenv install
      - go version
      - go env -w GOPROXY=direct
      - go env -w GO111MODULE=on
      - make init
  pre_build:
    commands:
      - make test
  build:
    on-failure: ABORT
    commands:
      - make release

artifacts:
  files:
    - '**/*'
  base-directory: dist
