# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rest_api.models.base_model_ import Model
from rest_api.models.run_status import RunStatus
from rest_api import util

from rest_api.models.run_status import RunStatus  # noqa: E501

class RunListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, runs=None, next_page_token=None):  # noqa: E501
        """RunListResponse - a model defined in OpenAPI

        :param runs: The runs of this RunListResponse.  # noqa: E501
        :type runs: List[RunStatus]
        :param next_page_token: The next_page_token of this RunListResponse.  # noqa: E501
        :type next_page_token: str
        """
        self.openapi_types = {
            'runs': List[RunStatus],
            'next_page_token': str
        }

        self.attribute_map = {
            'runs': 'runs',
            'next_page_token': 'next_page_token'
        }

        self._runs = runs
        self._next_page_token = next_page_token

    @classmethod
    def from_dict(cls, dikt) -> 'RunListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RunListResponse of this RunListResponse.  # noqa: E501
        :rtype: RunListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def runs(self):
        """Gets the runs of this RunListResponse.

        A list of workflow runs that the service has executed or is executing. The list is filtered to only include runs that the caller has permission to see.  # noqa: E501

        :return: The runs of this RunListResponse.
        :rtype: List[RunStatus]
        """
        return self._runs

    @runs.setter
    def runs(self, runs):
        """Sets the runs of this RunListResponse.

        A list of workflow runs that the service has executed or is executing. The list is filtered to only include runs that the caller has permission to see.  # noqa: E501

        :param runs: The runs of this RunListResponse.
        :type runs: List[RunStatus]
        """

        self._runs = runs

    @property
    def next_page_token(self):
        """Gets the next_page_token of this RunListResponse.

        A token which may be supplied as `page_token` in workflow run list request to get the next page of results.  An empty string indicates there are no more items to return.  # noqa: E501

        :return: The next_page_token of this RunListResponse.
        :rtype: str
        """
        return self._next_page_token

    @next_page_token.setter
    def next_page_token(self, next_page_token):
        """Sets the next_page_token of this RunListResponse.

        A token which may be supplied as `page_token` in workflow run list request to get the next page of results.  An empty string indicates there are no more items to return.  # noqa: E501

        :param next_page_token: The next_page_token of this RunListResponse.
        :type next_page_token: str
        """

        self._next_page_token = next_page_token
